var userNames = {
  memberURL: 'https://sp3cves.socialmedialink.com/',
  memberEmail: 'arya@yopmail.com',
  memberPassword: '12345678',
  adminURL: 'https://admin.socialmedialink.com',
  adminEmail: 'sp3cves@yopmail.com',
  adminPassword: 'General123$',
  superAdminEmail: 'tripthi.testmember17@socialmedialink.com',
  superAdminPass: 'General123$',
  account_no: 168,
  sprint: 'sp3asmi',
  memberFirstName: 'first',
  memberLastName: 'last',
  zipCode: '07093',
  birthDay: '10/10/1991',
  member2Email:'Jimysnow@yopmail.com',
  member2Password:'general1234',
  member2FirstName:'Jims',
  member2LastName:'Snow',
  adminPassword: 'General123$',
  facebookEmail: 'tripthi.testmember19@socialmedialink.com',
  facebookPass: 'general1234',
  facebookEmail2: 'tripthi.shetty@socialmedialink.com',
  facebookPass2: 'qwerty$',
  twitterEmail: 'sukada.ramakrishna@socialmedialink.com',
  twitterPass: 'general1234',
  twitterEmail2: 'tripthi.testmember20@socialmedialink.com',
  twitterPass2: 'general1234',
  instagramUserName: 'tripthi.shetty',
  instagramPass: 'abcd1234',
  path: 'C:/Users/you/Downloads/',
  //path_local: '/Users/tripthi/Desktop/Nightwatch/Images/',
  path_local: 'C:/Users/Tripthi/Desktop/Nightwatch/Images/',
  memberEmailFemale: 'leena@yopmail.com',
  darDate:"(//td[@class='day'])[19]",
  uin:'12448',
  member2Email:'Jimysnow@yopmail.com',
  member2Password:'general1234',
  member2FirstName:'Jims',
  member2LastName:'Snow',
  pinterestUserName:'sukadamr',
  usAddressLine1:'42',
  usAddressLine2:'Mohawk Ave',
  usCity:'Rockaway',
  caAddressLine1:'1010',
  caAddressLine2:'EASY ST',
  caCity:'OTTAWA',
  postalCode:'K1A 0B1',
  memberNewEmail: 'sukrao1@yopmail.com',
  memberNewPassword:'12345678',
  memberId:'99463',
  resetPassword: '87654321'
   };

module.exports = {
  
  userNames: userNames

 
}